# Generated by Django 5.0.1 on 2026-09-12 12:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the equipment', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the equipment')),
                ('equipment_type', models.CharField(help_text='Type/category of equipment (e.g., 3D Printer, Microscope)', max_length=100)),
                ('location', models.CharField(help_text='Physical location of the equipment', max_length=200)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('MAINTENANCE', 'Under Maintenance'), ('DISABLED', 'Disabled')], default='AVAILABLE', help_text='Current operational status of the equipment', max_length=20)),
                ('max_booking_duration', models.PositiveIntegerField(help_text='Maximum booking duration in hours', validators=[django.core.validators.MinValueValidator(1)])),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when equipment was added')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when equipment was last updated')),
            ],
            options={
                'verbose_name': 'Equipment',
                'verbose_name_plural': 'Equipment',
                'db_table': 'equipment',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['status'], name='equipment_status_92035a_idx'), models.Index(fields=['equipment_type'], name='equipment_equipme_f4cc15_idx'), models.Index(fields=['location'], name='equipment_locatio_282c00_idx'), models.Index(fields=['status', 'equipment_type'], name='equipment_status_97b293_idx')],
            },
        ),
    ]
