# Generated by Django 5.0.1 on 2026-09-12 13:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UsageLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(help_text='User role (STUDENT, FACULTY)', max_length=10, unique=True)),
                ('max_weekly_hours', models.PositiveIntegerField(help_text='Maximum booking hours per week')),
            ],
            options={
                'verbose_name': 'Usage Limit',
                'verbose_name_plural': 'Usage Limits',
                'db_table': 'usage_limits',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(help_text='Booking start time')),
                ('end_time', models.DateTimeField(help_text='Booking end time')),
                ('status', models.CharField(choices=[('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed'), ('NO_SHOW', 'No Show')], default='CONFIRMED', help_text='Current status of the booking', max_length=20)),
                ('cancellation_reason', models.TextField(blank=True, help_text='Reason for cancellation (if applicable)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when booking was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when booking was last updated')),
                ('equipment', models.ForeignKey(help_text='Equipment being booked', on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='equipment.equipment')),
                ('user', models.ForeignKey(help_text='User who made the booking', on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bookings',
                'ordering': ['-start_time'],
                'indexes': [models.Index(fields=['user', 'status'], name='bookings_user_id_1eeb34_idx'), models.Index(fields=['equipment', 'status'], name='bookings_equipme_455275_idx'), models.Index(fields=['start_time', 'end_time'], name='bookings_start_t_b42a03_idx'), models.Index(fields=['equipment', 'start_time', 'end_time'], name='bookings_equipme_0f6765_idx'), models.Index(fields=['status', 'start_time'], name='bookings_status_28164a_idx')],
            },
        ),
    ]
