# Generated by Django 5.0.1 on 2026-09-12 16:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0003_create_default_usage_limits'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(help_text='Maintenance start time')),
                ('end_time', models.DateTimeField(help_text='Maintenance end time')),
                ('reason', models.TextField(help_text='Reason for maintenance')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when maintenance was scheduled')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when maintenance was last updated')),
                ('created_by', models.ForeignKey(help_text='Admin who scheduled the maintenance', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_maintenance', to=settings.AUTH_USER_MODEL)),
                ('equipment', models.ForeignKey(help_text='Equipment under maintenance', on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_records', to='equipment.equipment')),
            ],
            options={
                'verbose_name': 'Maintenance',
                'verbose_name_plural': 'Maintenance Records',
                'db_table': 'maintenance',
                'ordering': ['-start_time'],
                'indexes': [models.Index(fields=['equipment', 'start_time', 'end_time'], name='maintenance_equipme_8a199d_idx'), models.Index(fields=['start_time', 'end_time'], name='maintenance_start_t_e4f5ce_idx')],
            },
        ),
        migrations.CreateModel(
            name='WaitingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_start_time', models.DateTimeField(help_text='Requested booking start time')),
                ('requested_end_time', models.DateTimeField(help_text='Requested booking end time')),
                ('position', models.PositiveIntegerField(help_text='Position in the waiting list (FIFO)')),
                ('status', models.CharField(choices=[('WAITING', 'Waiting'), ('NOTIFIED', 'Notified'), ('CANCELLED', 'Cancelled'), ('FULFILLED', 'Fulfilled')], default='WAITING', help_text='Current status of the waiting list entry', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when added to waiting list')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when entry was last updated')),
                ('equipment', models.ForeignKey(help_text='Equipment being requested', on_delete=django.db.models.deletion.CASCADE, related_name='waiting_list_entries', to='equipment.equipment')),
                ('user', models.ForeignKey(help_text='User on the waiting list', on_delete=django.db.models.deletion.CASCADE, related_name='waiting_list_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Waiting List Entry',
                'verbose_name_plural': 'Waiting List',
                'db_table': 'waiting_list',
                'ordering': ['equipment', 'position', 'created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='waiting_lis_user_id_958403_idx'), models.Index(fields=['equipment', 'status', 'position'], name='waiting_lis_equipme_cc3bf3_idx'), models.Index(fields=['equipment', 'requested_start_time', 'requested_end_time'], name='waiting_lis_equipme_8608eb_idx'), models.Index(fields=['status', 'position'], name='waiting_lis_status_03dd13_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='waitinglist',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'WAITING')), fields=('user', 'equipment', 'requested_start_time', 'requested_end_time', 'status'), name='unique_active_waiting_entry'),
        ),
    ]
